name: Sitemap

on:
  schedule:
    - cron: '0 0 * * SUN'

jobs:
  sitemap:
    name: Generate sitemap
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
      - run: npx sitemap-generator-cli -f projects/commudle-admin/src https://commudle.com/

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update sitemap
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: automated-sitemap
          title: 'Sitemap Update'
